version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bi-api
    environment:
      - PORT=${PORT:-8080}
      - ENV=${ENV}
    ports:
      - 8080:${PORT:-8080}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres"
    container_name: bi_psql
    env_file:
      - ./backend/${ENV:-dev}.env
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  web-server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bi-front
    ports:
      - 8081:80
    depends_on:
      - server
